### ISSUE TITLE
No statistics are updated

### ISSUE THREAD

**Issue by jmsferGH** [Microsoft/tigertoolbox#10]
hi,

this vesion of the usp_AdaptiveIndexDefrag isn't updating statistics. Not even the ones on the tables wich have fragmented indexes.

with the following parameters i get 551 indexes to bedefragmented but 0 statistics to be updated.

the table tbl_AdaptiveIndexDefrag_Working  is always empty.

==================================
EXEC dbo.usp_AdaptiveIndexDefrag		
		  @Exec_Print = 0	
		, @printCmds = 1
		, @updateStats = 1
		, @updateStatsWhere = 0	
		, @debugMode = 1	
		, @outputResults = 1
		, @forceRescan = 1	
		, @maxDopRestriction = 2	
		, @minPageCount = 8	
		, @maxPageCount = NULL	
		, @minFragmentation = 1	
		, @rebuildThreshold = 1
		, @rebuildThreshold_cs = 1
		, @defragDelay = '00:00:05'	
		, @defragOrderColumn = 'range_scan_count'	
		, @dealMaxPartition = NULL
		, @disableNCIX = 1
		, @offlinelocktimeout = 180
		, @scanMode = 'DETAILED'
		, @statsSample = 'FULLSCAN';

Validating options...
Starting up...

Executing AdaptiveIndexDefrag v1.6.3.1 on Microsoft SQL Server 2012 (SP3-CU2) (KB3137746) - 11.0.6523.0 (X64) 
	Mar  2 2016 21:29:16 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
.

OUTPUT OF THE DEBUG
=========================
The selected parameters are:
Defragment indexes with fragmentation greater or equal to 1;
Rebuild indexes with fragmentation greater than 1;
Rebuild columnstore indexes with fragmentation greater than 1;
Non-clustered indexes will be disabled prior to rebuild;
Defragment ALL indexes;
Commands WILL NOT be executed automatically;
Defragment indexes in DESC order of the RANGE_SCAN_COUNT value;
Time limit was specified and is 480 minutes;
ALL databases will be defragmented;
ALL tables will be defragmented;
We WILL be rescanning indexes;
The scan will be performed in DETAILED mode;
LOBs will be compacted;
Limit defrags to indexes with more than 8 pages;
Indexes will be defragmented OFFLINE;
Indexes will be sorted in the DATABASE;
Indexes will have its ORIGINAL Fill Factor;
All partitions will be considered;
**Statistics WILL be updated on all stats belonging to parent table;**
Statistics will be updated with FULLSCAN.
Statistics will be updated with Incremental property (if any) not changed from current setting.
Defragmentation will use system defaults for processors;
Lock timeout is set to 180 for offline rebuilds;
From SQL Server 2014, lock timeout is set to 5 for online rebuilds;
From SQL Server 2014, lock timeout action is set to SELF for online rebuilds;
 DO print the sql commands;
 DO output fragmentation levels;
Wait 00:00:05 (hh:mm:ss) between index operations;
Execute in DEBUG mode.

Listing databases...
Retrieving list of databases to loop, excluding Always On secondary replicas...
Cross checking with exceptions for today...
Preparing for new database scan...
Scanning database(s)...
 Looping through list of databases and checking for fragmentation...
  Working on msdb...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
.
.
.
.
.
.
.
  Working on DBA...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
 Listing and removing disabled indexes (except those disabled by the defrag cycle itself) or hypothetical indexes from loop...
 Updating Exception mask for any index that has a restriction on the days it CANNOT be defragmented...
Looping through batch list... There are 551 indexes to defragment in 9 database(s)!
**Looping through batch list... There are 0 index related statistics to update in 0 database(s), plus 0 other statistics to update in 0 database(s)!**
 Printing SQL statements...
 Selecting an index to defragment...

**Comment by pmasl** [comment]
Can you please try with the updated version?
This is what I get:

Validating options...
Starting up...

Executing AdaptiveIndexDefrag v1.6.3.1 on Microsoft SQL Server 2016 (RTM-GDR) (KB3164398) - 13.0.1708.0 (X64) 
	Jun  2 2016 07:18:56 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Enterprise 6.3 <X64> (Build 14393: ) (Hypervisor)
.
The selected parameters are:
Defragment indexes with fragmentation greater or equal to 1;
Rebuild indexes with fragmentation greater than 1;
Rebuild columnstore indexes with fragmentation greater than 1;
Non-clustered indexes will be disabled prior to rebuild;
Defragment ALL indexes;
Commands WILL NOT be executed automatically;
Defragment indexes in DESC order of the RANGE_SCAN_COUNT value;
Time limit was specified and is 480 minutes;
ALL databases will be defragmented;
ALL tables will be defragmented;
We WILL be rescanning indexes;
The scan will be performed in DETAILED mode;
LOBs will be compacted;
Limit defrags to indexes with more than 8 pages;
Indexes will be defragmented OFFLINE;
Indexes will be sorted in the DATABASE;
Indexes will have its ORIGINAL Fill Factor;
All partitions will be considered;
Statistics WILL be updated on all stats belonging to parent table;
Statistics will be updated with FULLSCAN.
Statistics will be updated with Incremental property (if any) not changed from current setting.
Defragmentation will use 2 processors;
Lock timeout is set to 180 for offline rebuilds;
From SQL Server 2014, lock timeout is set to 5 for online rebuilds;
From SQL Server 2014, lock timeout action is set to SELF for online rebuilds;
 DO print the sql commands;
 DO output fragmentation levels;
Wait 00:00:05 (hh:mm:ss) between index operations;
Execute in DEBUG mode.

Listing databases...
Retrieving list of databases to loop, excluding Always On secondary replicas...
Cross checking with exceptions for today...
Preparing for new database scan...
Scanning database(s)...
 Looping through list of databases and checking for fragmentation...
  Working on msdb...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Getting columnstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
  Working on AdventureWorks2016CTP3...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Getting columnstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
  Working on AdventureworksDW2016CTP3...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Getting columnstore indexes...
Warning: The join order has been enforced because a local join hint is used.
    Looking up additional index information...
    Looking up additional statistic information...
  
(...)

  Working on TestOracle...
   Building list of objects in database...
      Filtering indexes according to ixtypeOption parameter...
    Getting rowstore indexes...
    Getting columnstore indexes...
    Looking up additional index information...
    Looking up additional statistic information...
 Listing and removing disabled indexes (except those disabled by the defrag cycle itself) or hypothetical indexes from loop...
 Updating Exception mask for any index that has a restriction on the days it CANNOT be defragmented...
**Looping through batch list... There are 47 indexes to defragment in 10 database(s)!
Looping through batch list... There are 44 index related statistics to update in 8 database(s), plus 848 other statistics to update in 14 database(s)!**

**Comment by pmasl** [comment]
Fixed with v1.6.3.2. Was working for 2014 and 2016 though. Thanks!
