### ISSUE TITLE
Script is case-insensitive

### ISSUE THREAD

**Issue by JohnKNess** [microsoft/tigertoolbox#116]
When running the script on a `Latin1_General_CS_AS` instance, I received the following error message:

> Msg 208, Level 16, State 1, Line 74
> Invalid object name 'MASTER.sys.databases'.

I guess it's because the `master` database is lower-case.

**Comment by sm8680** [comment]
I've run into this situation in a few places with the code.  In theory the queries need to be tested against a case sensitive collation.

**Comment by pmasl** [comment]
@sm8680 you are correct and it hasn't yet.

**Comment by sm8680** [comment]
I recall a MASTER being in upper case at one point but I was unable to find it.  But here’s a few in the bp check.
SPROC: usp_bpcheck
Due to case sensitivity has 4 unresolved issues. 
In a SQL Server Data tools project
Line 145: OBJECT_ID
FROM master.sys.all_objects a (NOLOCK) INNER JOIN master.sys.database_permissions b (NOLOCK) ON a.[OBJECT_ID] = b.major_id
needs to be 
FROM master.sys.all_objects a (NOLOCK) INNER JOIN master.sys.database_permissions b (NOLOCK) ON a.[object_id] = b.major_id
Line 5545: Name
IF (SELECT COUNT([Name]) FROM master.sys.configurations WHERE [value] <> [value_in_use] AND [is_dynamic] = 0) > 0
needs to be 
IF (SELECT COUNT([name]) FROM master.sys.configurations WHERE [value] <> [value_in_use] AND [is_dynamic] = 0) > 0

Line 5548: Name
SELECT 'Instance_checks' AS [Category], 'System_Configurations_Pending'AS [Information], [Name] AS [Setting],
needs to be
SELECT 'Instance_checks' AS [Category], 'System_Configurations_Pending'AS [Information], [name] AS [Setting],

Line 9097: @dbName
SET @sqlcmdTR = 'USE ' + QUOTENAME(@dbName) + '; SELECT @HasRI_OUT = COUNT(*) FROM sys.dm_db_tuning_recommendations'
Needs to change to
SET @sqlcmdTR = 'USE ' + QUOTENAME(@dbname) + '; SELECT @HasRI_OUT = COUNT(*) FROM sys.dm_db_tuning_recommendations'

Also I’ve been unable to deploy this sproc with SQL Server Data Tools from a sqlcmd file as well as via an SSA Job.  Due to line 3256
SET @Text1 = '$myWindowsID=[System.Security.Principal.WindowsIdentity]::GetCurrent()
I believe the $ is the issue.


Just an FYI - Exploring the Plan Cache 
Turning them into stored procedures will require that the first statement to be a semi colon.  Otherwise a syntax error will occur.
WITH XMLNAMESPACES 
to
;WITH XMLNAMESPACES

**Comment by pmasl** [comment]
Thank you for these findings. They're fixed in the latest version.
